### ISSUE TITLE
Idris2 LSP Response Buffer is empty

### ISSUE THREAD

**Issue by Qumeric** [idris-community/idris2-nvim#27]
I installed idris2-nvim and it seems to mostly work (e.g. if I have a syntax error it highlights the line and shows error).

However, if I do idris2.hover.open_split(), it opens the buffer but it is always empty. I also never have any popups appearing unless I do something like "evaluate" (seems like they should appear passively although I am not completely sure).

Due to this problem, I am not able to check types and usability is significantly limited.

I have neovim 0.9.0 on Manjaro Linux.

**Comment by Qumeric** [comment]
I don't see any new entries in :LspLog when I do `open_split()`. Seems like it just doesn't communicate with the server for some reason.

Also, I am not quite sure if it is the right place to report this, please tell me if it's not.

**Comment by Qumeric** [comment]
Oh, I think I figured it out, I just need to do `vim.lsp.buf.hover()` manually. 

I assumed that it will run automatically, not sure if it was the intention. Feel free to close the issue if it wasn't.

**Comment by Russoul** [comment]
An excerpt from `docs/idris2-nvim.txt`
<img width="481" alt="image" src="https://github.com/user-attachments/assets/750c31e9-5dfc-4819-b19c-deb3800820da">

So yep, expected behaviour.
